### ISSUE TITLE
请问FPPhysics库是在哪里实现的呢？

### ISSUE THREAD

**Issue by owllyi** [PxGame/XMLib.AM#1]
打开USE_FIXPOINT之后报错，找了半天没找到FPPhysics在哪里，求FPPhysics库~

**Comment by PxGame** [comment]
改装的一个开源库 [bepuphysics1int](https://github.com/sam-vdp/bepuphysics1int)
里面有很多东西不适配Unity，我都适配了的。
只能勉强用用，性能很差，有时间还是得自己写😂

使用 USE_FIXPOINT，是为了方便修改别名，避免直接修改代码。如果有别的引擎，直接改别名就行了，类似c++的宏的作用。

**Comment by owllyi** [comment]
感谢回复，这个bepuphysics1int修改版在您的仓库里是哪个工程啊，下载的XMLib.AM系列里没有包含这个库吧。

**Comment by PxGame** [comment]
对，没有包含在里面，我打压缩包，放在群共享了，你可以在群里获取。慎用... 我只是写Demo用一下。

**Comment by owllyi** [comment]
收到，多谢
